data:
  original_root: "data/Mescalina 2017"
  augmented_root: "data/Mescalina 2017_augmented"

model:
  base_model: "facebook/wav2vec2-base-960h"
  hidden_dim: 768
  num_emotions: 8

training:
  batch_size: 16          # 改大一点，原型更稳定
  learning_rate: 1e-4
  epochs: 100
  device: "cuda"
  patience: 10

loss:
  lambda_cls: 1.0
  lambda_proto: 0.5
  lambda_emer: 0.7        # 稍微提高，让大小犬更一致